apiVersion: v1
kind: Service
metadata:
  name: casting-api-service
spec:
  type: NodePort # 로컬 테스트 환경(minikube 등)에서 쉽게 접근하기 위한 타입
  selector:
    app: casting-api # 이 서비스가 트래픽을 전달할 Pod를 선택
  ports:
    - protocol: TCP
      port: 80 # 클러스터 내부에서 사용할 포트
      targetPort: 8000 # Pod의 컨테이너가 노출하는 포트
      nodePort: 30007 # 클러스터 외부에서 접근할 포트 (30000-32767 사이)
